[package]
name = "gssa-rust"
version = "0.1.0"
authors = ["Nicola Papale"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba = { version = "0.5.0-pre", git = "https://github.com/nicopap/gba.git", branch = "const-generics-voladdr" }
voladdress = "0.3"
rubidium = { version = "0.0.17", features = ["unsafe_addresses"] }


[profile.release]
lto = true
panic = "abort"
incremental = false
codegen-units = 1
