[package]
name = "gssa-rust"
version = "0.1.0"
authors = ["Nicola Papale"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["runtime_asserts"]
runtime_asserts = []

[dependencies]
gba = { version = "0.5.3", path = "../../git/gba" }
voladdress = "0.4"
const-default = { version = "1.0", default-features = false, features = ["derive"] }

[profile.release]
lto = true
panic = "abort"
incremental = false
codegen-units = 1
