[package]
name = "include_const_aligned"
description = "A macro to incldue_bytes, but aligned, that can be assigned to a constant"
version = "0.4.0"
authors = ["Nicola Papale"]
edition = "2021"
license = "Zlib OR Apache-2.0"
