[package]
name = "volmatrix"
description = "Additional methods and structs for the voladdress crates"
version = "0.4.0"
authors = ["Nicola Papale"]
edition = "2021"
license = "Zlib OR Apache-2.0"

[features]
default = []
nightly = []

[dependencies]
voladdress = "0.4"
